default_language_version:
    python: python3.13

repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        files: (phoibe|tests)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo:  https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        files: \.ipynb$
        args: ["--fix", "--config=pyproject.toml", "--show-files"]
      - id: nbqa-black

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        args: ["phoibe"]
        pass_filenames: false
        additional_dependencies: [pandas-stubs, types-PyYAML, types-requests, types-python-dateutil]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=775"]

  - repo: https://github.com/jshwi/docsig
    rev: intellij-plugin-v1.0.2
    hooks:
      - id: docsig
        files: "pho/"